packer {
  required_plugins {
    amazon = {
      version = ">= 0.0.2"
      source  = "github.com/hashicorp/amazon"
    }
  }


source "amazon-ebs" "autogenerated_1" {
  access_key    = "AKIAVIBYHL3KFDB3WTGR"
  secret_key    = "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"
  ami_name      = "ubuntu-ingnix-proj"
  instance_type = "t2.micro"
  region        = "us-east-1"
I source_ami = "ami-0574da719dca65348"
  ssh_username  = "ubuntu"
} 

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "shell" {
    inline = ["sleep 30", "echo Hello world!", "sudo apt update -y", "sudo apt install nginx -y"]
  }

}
